### ISSUE TITLE
克隆的时候报错RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by ayaup** [kbdxbt/kbframe#1]
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

经查资料...解决方案, 待验证.

增大缓存区

Git config --global http.postBuffer 524288000

**Comment by kbdxbt** [comment]
多试几次就可以了，安装有啥不懂的可以直接加我qq。目前也在beta测试
